Developer instructions
cms-gem-daq-project/gem-plotting-tools pull request #125
Opened 2018-07-04 14:53 UTC by lmoureaux

## Description

(On top of #123)

Add instructions for developers to the Sphinx documentation:

* Duplicate the user setup instructions
* Duplicate the developer instructions from `.github/CONTRIBUTING.md`
* Add developer setup instructions and documentation guidelines

The concerns raised in #121 are also addressed in this PR.

Since Github has basic support for rendering `rst`, I could add a link to developer docs in the README. However, cross-references don't work, and the rendering is much worse than what Sphinx does.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

We need to document how to set up a development area and test changes.

## How Has This Been Tested?

The instructions are based on https://gist.github.com/jsturdy/4f9bccbdd18d953f73777e492a71fd24, my own experience as a developer and support I did privately on Mattermost.

### Screenshots (if appropriate)

Better than a screenshot, [a link to the documentation](http://homepage.iihe.ac.be/~lmoureau/GEM/sphinx/html/index.html)!

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-07-04 18:05 UTC, bdorney commented
Does this supersede https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/123 or require https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/123?

2018-07-04 18:11 UTC, bdorney commented on doc/coding.rst
> +    pip install -U rpm/gempython_gemplotting-1.0.0.tar.gz
The developer `gist` has this done with option `-I` to ignore and force re-install.  In some cases I've found that the `-U` does not always overwrite correctly previously installed files.  Would suggest to have `-I`.

2018-07-04 18:12 UTC, bdorney commented on doc/coding.rst
> +  * Once that feature is completed, create a pull request
We should also apply the same hotfix to develop.  Add a line here.

2018-07-04 18:17 UTC, bdorney requested changes
two small changes needed. Otherwise very good.  Some clarification of which PR's this needs/replaces required.

2018-07-04 18:17 UTC, bdorney commented
Does this also superseded: https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/121?

2018-07-04 23:13 UTC, lmoureaux commented
No PR is superseded. This one (#125) is built on top of #123 since I expect #123 to be merged before (but it's not required and I can rebase off current `develop`). It also fixes the issue that prevents #121 from being merged (#121 will need a rebase).

2018-07-09 14:29 UTC, lmoureaux commented
* Rebased on top of `develop`
* Made the requested changes

2018-07-11 14:21 UTC, bdorney commented
This PR is out of date with develop.  Can you update it?  Then I'll approve it.

2018-07-11 16:15 UTC, lmoureaux commented
Rebased.

2018-07-13 09:01 UTC, bdorney approved these changes

2018-07-14 13:03 UTC, mexanick approved these changes

2018-07-15 11:05 UTC, merged