getDirByAnaType raises KeyError for bad anaType
cms-gem-daq-project/gem-plotting-tools pull request #243
Opened 2019-08-13 12:27 UTC by bdorney

## Description

Function `getDirByAnaType()` will no longer exit if input argument `anaType` is not in list of accepted types (`ana_config`) but will instead raise a `KeyError` which can be caught as an exception.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

Breaking because instead of exiting it will raise an error.

## Motivation and Context

QOL; allow developers opportunity to catch bad `anaType` and handle this instead of automatically exiting.

## How Has This Been Tested?

Change was trivial.

### Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-08-13 15:39 UTC, jsturdy commented
Is there an example where this functionality will be beneficial (catching rather than simply exiting)?

2019-08-14 08:52 UTC, bdorney commented
> Is there an example where this functionality will be beneficial (catching rather than simply exiting)?

Off the top of my head no.  But I think in general it might be better coding practice to generate an exception in an API function then exit in an manner that does *not* raise a `SystemExit` exception.  Especially as new developers come in and may not be familiar with the API...it may be difficult for them to trace down what's going on and raising an exception will ensure a stack trace.

2019-08-14 12:14 UTC, jsturdy requested changes

2019-08-14 12:14 UTC, jsturdy commented on utils/anautilities.py
> +        raise KeyError("getDirByAnaType - Invalid anaType argument; please select only from the list: {:s}".format(ana_config.keys()))
Probably useful to print the type that was specified

2020-04-09 19:25 UTC, lpetre-ulb commented
Should this PR be merged or close? The change seems trivial, but the PR require a rebase and a small change.

2020-05-06 09:57 UTC, closed without merging