[Bug Fix] This is to fix an indexing issue causing problems in qc7/8
cms-gem-daq-project/gem-plotting-tools pull request #268
Opened 2019-11-26 13:49 UTC by bregnery

This is a problem observed in qc7/8 but not in my own venv.

## Description
This should fix the sbitThresh analysis

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context
Required to work in the qc7/8 environment

## How Has This Been Tested?
```bash
#!/usr/bin/env bash

#=========================================================================================
# Testing Suite for the Inflection Point finder ------------------------------------------
#=========================================================================================

echo "Welcome to Brendan's Testing Suite for the Inflection Point Finder"
echo "------------------------------------------------------------------------------------"
echo "This script executes a bunch of files known to cause issues for the inflection"
echo "point finder"
echo "------------------------------------------------------------------------------------"

echo "Did you remember to update??? With make pip and pip install rpm*.tar.gz?"

echo "File 1"
echo "This tests how the code handles a vfat with a bad vfat"
echo "Please make sure (2,5,4) is filled in your system_specfic_constants.py file"

# This file causes issues because of a zero slope issue
anaSBitThresh.py /data/bigdisk/GEM-Data-Taking/GE11_QC8//sbitRate/channelOR/2019.10.25.13.59/SBitRateData.root

echo "File 2"
echo "This tests how the code handles a detector with missing vfats"
echo "Please make sure (1,2,0) is filled in your system_specfic_constants.py file"

# This file is from the coffin where the detector is missing vfats
anaSBitThresh.py /data/bigdisk/GEM-Data-Taking/GE11_Integration//sbitRate/channelOR//2019.10.24.17.45/SBitRateData.root
```

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2019-11-26 13:53 UTC, jsturdy commented
What are the versions of dependencies in the two environments?

2019-11-26 13:53 UTC, bregnery commented
how do I figure that out?

2019-11-26 15:28 UTC, jsturdy commented
probably something like `pip freeze` from your environment, as well as the same for QC8
mostly interested in `numpy`/`root_numpy`/`pandas`, not sure there are other relevant deps

2019-11-26 15:37 UTC, bregnery commented
This bug also does not affect the p5 computer

2019-11-26 15:38 UTC, bregnery commented
For numpy:
```bash
(inflectionEnv)-bash-4.2$ pip show numpy
Name: numpy
Version: 1.14.6
```

2019-11-26 16:21 UTC, jsturdy commented
which version is at P5? which version is on QC8 in the environment that is being used there?

2019-12-02 15:32 UTC, jsturdy commented
OK, I'm going to make an executive decision and we'll run `numpy==1.16.5` and `root_numpy==4.8.0` on our production machines (so code **must** be tested to work with at least these)

2019-12-02 15:33 UTC, jsturdy commented
@bregnery needs another rebase, and can you make sure it works as expected based on the aforementioned versions?

2019-12-02 15:47 UTC, bregnery commented
Okay, it works with the new requirements. Now I just need to re-base.

2019-12-02 15:53 UTC, bregnery commented
Done

2019-12-02 15:56 UTC, jsturdy reviewed
Can you update the relevant requirements files? (`requirements.txt`, `pkg/setup.cfg`, etc)

2019-12-10 13:41 UTC, jsturdy commented
@bregnery bump

2019-12-12 14:11 UTC, bregnery commented
updated and it compiles/runs. But @jsturdy, I think that the requirements might not be getting parsed correctly.

2019-12-12 16:17 UTC, jsturdy requested changes

2019-12-12 16:17 UTC, jsturdy commented on pkg/setup.cfg
>             numpy >= 1.7
this version should match the one in the requirements, which i think can be `>=1.14` for the features actually in use

2019-12-12 16:17 UTC, jsturdy commented on pkg/setup.cfg
> +           root_numpy >= 4.8
this also doesn't need to change, things work fine with `4.7`

2019-12-13 11:18 UTC, jsturdy approved these changes
:+1:

2019-12-13 11:19 UTC, merged