Converting nVFats to nVFATS everywhere
cms-gem-daq-project/gem-plotting-tools pull request #284
Opened 2020-01-30 11:50 UTC by mexanick

Providing a name standartization/typo fixes. The code has been tested in venv on QC7 PC. 
## Description

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-01-30 13:30 UTC, jsturdy requested changes
minor cleanup, probably rebase on top of #283 once its merged

2020-01-30 13:30 UTC, jsturdy commented on utils/scurveAlgos.py
> +                nVFATS = nVFATS,
clean up extra whitespace conflicting with nearby style?

2020-01-31 09:33 UTC, jsturdy commented
ready for rebase following fixup

2020-01-31 09:41 UTC, mexanick commented
should be ready to go

2020-01-31 09:47 UTC, jsturdy approved these changes
:+1: (also for the extra whitespace cleanup, which i ignored for the review :-D)

2020-01-31 09:48 UTC, merged